### ISSUE TITLE
Logo suite with many logos + reduced motion

### ISSUE THREAD

**Issue by enstyled** [primer/brand#413] opened 2023-09-04 12:08 UTC
The `Logo suite` marquee collapses when overflowing, when using reduced motion. It's nice that it is showing all the logos, but might be a problem when collapsing to 2-3 rows, or if only one of the logos is wrapping on a second line, making it look broken.

Perhaps keeping the logos in a single line, while hiding some of them is a better alternative?

![Image](https://github.com/primer/brand/assets/621097/5862c86e-98ea-44b3-a9ce-021deb2eee2e)

**Comment by simurai** [comment] 2023-09-05 01:52
> Perhaps keeping the logos in a single line, while hiding some of them is a better alternative?

Was wondering about this too.

Maybe a simple solution would be to randomly order the logos on each page load and then only show enough logos to fit one line. But not sure if that would be ok with sponsors that pay money to appear on the page? Maybe depends what the contract says or it needs some extra clause like "logo placement is random and not guaranteed". 🤔

**Comment by rezrah** [comment] 2023-09-05 15:06
👋 This was discussed at Primer Brand planning earlier this week, with @enstyled in attendance.

Outcome:

- Wrapping of logos is intended behaviour when reduced motion preferences are enabled. This is because we are removing the marquee effect altogether and instead presenting the logos to the user immediately sans animation. Wrapping doesn't happen when that preference is turned off.
- [Our guidelines for this component](https://primer.style/brand/components/LogoSuite#usage) are to use no more than 12 logos in a single logo bar. We recommend stacking LogoSuite components if you need to show more.

Closing this issue for now, as there's no further action planned.

**Closed by rezrah** 2023-09-05 15:06 UTC
Labels: brand
