### ISSUE TITLE
🐛 [BUG] - InlineLink does not inherit size

### ISSUE THREAD

**Issue by philernst** [primer/brand#446] opened 2023-10-04 18:02 UTC
### Describe the bug

Upgrading @primer/react-brand to 0.24.0 and higher causes `InlineLinks` to display as size 200 instead of inheriting their size from their parent element. [For example](https://resources.github.com/learn/pathways/automation/essentials/automated-application-deployment-with-github-actions-and-pages/):

![Screenshot with arrows pointing to improperly sized links](https://github.com/primer/brand/assets/7658603/162c31b3-9a99-48c4-880f-ef17513cb73c)

I tested @primer/react-brand 0.20.0 and 0.23.0 and the links display as expected:

![Screenshot with arrows pointing to properly sized links](https://github.com/primer/brand/assets/7658603/32c68f8e-974d-41ff-a34f-95543edd6d02)

### Reproduction steps

1. Create codespace for https://github.com/github/resources-hub
2. npm install @primer/react-brand@0.24.0
3. script/server
4. http://127.0.0.1:3000/learn/pathways/automation/essentials/automated-application-deployment-with-github-actions-and-pages/
5. Links do not inherit size from their parent element

### Expected behavior

1. Create codespace for https://github.com/github/resources-hub
2. npm install @primer/react-brand
3. script/server
4. http://127.0.0.1:3000/learn/pathways/automation/essentials/automated-application-deployment-with-github-actions-and-pages/
5. Links inherit size

### Screenshots

Above

### Browsers

Chrome

### OS

Mac

**Comment by msbise** [comment] 2023-10-10 19:52
@philernst is there an update on timing for this fix?

**Comment by philernst** [comment] 2023-10-10 23:50
Thanks for the ping @msbise! It looks like @jonrohan moved it to the queue 🤞

**Comment by rezrah** [comment] 2023-10-11 16:12
Update: @joseph-lozano will be picking this up.

**Comment by joseph-lozano** [comment] 2023-10-17 14:15
I've taken a look at this issue, and the reason for the breakage is due to custom CSS in ResourcesHub, specifically the [markdown-body-overrides](https://github.com/github/resources-hub/blob/e6720175277ba4905fad50e4deb46c0d9c3e1a31/src/styles/markdown-body-overrides.scss#L16).

In Primer Brand 0.24.0, the default text size was changed. Previously it matched the `$h3-size` in your CSS, which is why it worked in versions 0.23 and prior. I have tried to adjust the code in Primer Brand to be compatible with your Custom CSS, but unfortunately I was not able to make that change without causing other regressions.

There are a few options. 

1. I'd recommend moving to use our [Prose Component](https://primer.style/brand/components/Prose), which is designed for styling raw HTML for long form content. 
2. For something quicker, you could add the `span` tag to that list of overrides. This does leave open the possiblility for other CSS collisions however.

Let me know if it's alright to go ahead and close this issue, or if you need anything else!

**Comment by sergioalvz** [comment] 2023-10-18 11:43
hey @joseph-lozano! Thanks for taking the time to investigate this issue ✨

I think there is still an issue in how Primer Brand renders `InlineLink` inside `Heading` elements, though, since the `size` prop isn't correctly propagated (it works perfectly for `Text` elements). See the following example in Codepen: https://codepen.io/sergioalvz/pen/XWovjEj

**Comment by philernst** [comment] 2023-10-20 13:57
@joseph-lozano I removed the custom CSS and use react brand elements with [this update](https://github.com/github/resources-hub/pull/1030/commits/f4076bbdd48e3d69e5b75508378108532a480898). Interestingly, when I use an invalid value in the `size` attribute for  `InlineLink`, the font size works as expected. 🤔  That seems to "reset" the font size inheritance.

I recorded this video to show what I'm seeing.

https://github.com/primer/brand/assets/7658603/91dc18c5-02ba-4370-b7f8-b21af2b7ef56

What do you think?

**Comment by joseph-lozano** [comment] 2023-10-24 16:49
That behavior doesn't surprise me. 

We have a fix, it will make it out in the next release (following todays). It will be a breaking change. `InlineLink` will no longer accept a size a prop. It will now inherit whatever size its parent has. 

This means that it will now work the same the across both `Heading` and `Text` components.

This seemed like the best fix because `Heading` and `Text` elements follow different scales for sizing (and under the hood, `InlineLink` is a `Text` element).

When you upgrade to the version where this fix drops, you will have to remove the `size` prop from all `InlineLink`s.

**Closed** 2023-11-03 13:38 UTC
Labels: bug, brand
