### ISSUE TITLE
[Regression Issue] - `Card` component `max-width`

### ISSUE THREAD

**Issue by stamat** [primer/brand#813] opened 2024-11-06 15:00 UTC
Hey yo! ✨ 

The latest update of `primer/brand` with the introduction of `max-width: var(--brand-Card-maxWidth);` for the `Card` component introduced issues on dotcom marketing pages.

Why was this `maxWidth` introduced?

| Page | Before | After |
|----|----|----|
|/features/actions|![Image](https://github.com/user-attachments/assets/04caaeb3-2130-43c4-b4be-66c839f5542f)|![Image](https://github.com/user-attachments/assets/d1429244-b0af-4c40-af5c-a731d3083f17)|
|/features/issues|![Image](https://github.com/user-attachments/assets/8b8b92f4-7e69-4c29-9617-ec6c49d32ceb)|![Image](https://github.com/user-attachments/assets/8ac5748f-28ad-445e-b0a2-0c4f0674e342)|
|/features|![Image](https://github.com/user-attachments/assets/65e08bba-f9b6-4b38-b49a-470a3bf3d075)|![Image](https://github.com/user-attachments/assets/c4a95a8a-0ac9-45f0-a283-34b79c9cfd5e)|

**Comment by danielguillan** [comment] 2024-11-06 15:26
@stamat, that change was introduced in https://github.com/primer/brand/pull/781. It aimed to fix a bug where `fullWidth={false}` did not work as expected. Setting `fullWidth={true}` should resolve the issues you're experiencing. Please let us know if it doesn't.

**Comment by rezrah** [comment] 2024-11-10 20:15
Closed as the `fullWidth` prop will fix this, and confirming the max-width constraints are intended behaviour. @stamat let us know if you'd like a hand applying the updates.

**Closed by rezrah** 2024-11-10 20:15 UTC

**Comment by stamat** [comment] 2024-11-11 12:21
@rezrah @danielguillan applied the `fullWidth` on dotcom! Though I still think full width should be default.. Anyways, Thanks bros! 💖
